config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  resources :tests do
    resources :questions, shallow: true, except: :index
  end
end

app/models/answer.rb
# frozen_string_literal: true
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true

  validate :validate_max_answer, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def validate_max_answer
    errors.add(:max_answer) if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true
class Category < ApplicationRecord
  default_scope { order(:title) }

  has_many :tests, dependent: :destroy

  validates :title, presence: true
end

app/models/question.rb
# frozen_string_literal: true
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
# frozen_string_literal: true
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User', foreign_key: :author_id

  has_many :tests_users, dependent: :destroy
  has_many :users, through: :tests_users
  has_many :questions, dependent: :destroy

  validates :title, presence: true,
                    uniqueness: { scope: :level,
                                  message: :uniq_title_with_level }
  validates :level, numericality: { greater_than_or_equal_to: 0,
                                    only_integer: true }

  scope :easy_level, -> { where(level: 1) }
  scope :average_level, -> { where(level: 2..4) }
  scope :difficult_level, -> { where(level: 5..Float::INFINITY) }

  scope :all_with_category, ->(category) {
    joins(:category)
      .where(categories: { title: category })
      .order(title: :desc)
  }

  def self.all_with_category_array(category)
    all_with_category(category).pluck(:title)
  end
end

app/models/tests_user.rb
# frozen_string_literal: true
class TestsUser < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/user.rb
# frozen_string_literal: true
class User < ApplicationRecord
  has_many :authored_tests, class_name: 'Test', foreign_key: :author_id
  has_many :tests_users, dependent: :destroy
  has_many :tests, through: :tests_users

  validates :email, :password, presence: true

  def list_test_by_level(level)
    tests.where(level: level)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :find_test, only: %i[new create]
  before_action :find_question, only: %i[show edit destroy update]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_test_not_found
  def show; end

  def edit; end

  def new
    @question = @test.questions.build
  end

  def create
    @question = @test.questions.build(question_params)
    if @question.save
      redirect_to test_path(@test)
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to test_path(@question.test)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to root_path
  end

  private

  def question_params
    params.require(:question).permit(:body)
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def rescue_with_test_not_found
    render plain: 'Question not found'
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  before_action :find_test, only: %i[edit show update destroy]

  def index
    @tests = Test.all
  end

  def show
    @questions = @test.questions
  end

  def new
    @test = Test.new
  end

  def create
    @test = Test.new(test_params)
    if @test.save
      redirect_to @test
    else
      render :new
    end
  end

  def edit; end

  def update
    if @test.update(test_params)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @test.destroy
    redirect_to root_path
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end

  def test_params
    params.require(:test).permit(:title, :level, :category_id, :author_id)
  end

  def find_tests
    @tests = Test.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def question_header(question)
    if question.new_record?
      "Create New #{question.test.title} Question"
    else
      "Edit #{question.test.title} Question"
    end
  end

  def this_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to(repo.capitalize, "https://github.com/#{author}/#{repo}", target: '_blank')
  end

end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGuru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/questions/_question.html.erb
<tr>
  <td><%= question.id %></td>
  <td><%= question.body %></td>
  <td><%= link_to "Edit", edit_question_path(question) %></td>
  <td><%= link_to "Destroy", question, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td>
</tr>

app/views/questions/edit.html.erb
<h1><%= question_header(@question) %></h1>

<%= form_with model: [@test, @question], local: true do |f| %>

  <p>
    <%= f.label 'body:' %><br>
    <%= f.text_field :body %>
  </p>

  <%= f.submit %>
<% end %><br>

<%= link_to "Back", test_path(@question.test) %>

app/views/questions/new.html.erb
<h1><%= question_header(@question) %></h1>

<%= form_with model: [@test, @question], local: true do |f| %>

  <p>
    <%= f.label 'body:' %><br>
    <%= f.text_field :body %>
  </p>

  <%= f.submit %>
<% end %><br>

<%= link_to "Back", test_path(@test) %>

app/views/shared/_errors.html.erb
<% if resource.errors.present? %>
  <div>
    <h2>"#{resource.errors.count} error(s) detected: "</h2>

    <ul>
      <% resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <p>Year: <%= this_year %></p>
  <p>Author: Pavel-Devel</p>
  <p>Project name: <%= github_url('Pavel-devel', 'TestGuru--TN') %></p>
  <p><a href="https://thinknetica.com " target="_blank">Учебный проект в онлайн-школе Thinknetica</a></p>
</footer>